# This file was generated by GoReleaser. DO NOT EDIT.
cask "spotr" do
  version "0.2.0"

  on_macos do
    on_intel do
      sha256 "ce6d76942ab001e76aa1625695919e86ab5ddd7d192c19b74598b0532c340c38"
      url "https://github.com/Yokanater/spotr/releases/download/v#{version}/spotr_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "d510e0f98525b544e45b77480f348a4f89c94abd0bb04d713b6b0f5b5aa2adb7"
      url "https://github.com/Yokanater/spotr/releases/download/v#{version}/spotr_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "92300ab79b598c02c8fc1d7f9601b48a1a96435ccc4df24f4af53a61c7b45549"
      url "https://github.com/Yokanater/spotr/releases/download/v#{version}/spotr_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "e8b4f985d28a665e235686b20e78cfefca96854f3e06a3495eab2bd55dfff876"
      url "https://github.com/Yokanater/spotr/releases/download/v#{version}/spotr_Linux_arm64.tar.gz"
    end
  end

  name "spotr"
  desc "Workout logging for nerds on the terminal"
  homepage "https://spotr.info"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "spotr"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr",
                     args: ["-dr", "com.apple.quarantine", "#{staged_path}/spotr"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    spotr stores its database in your operating system's user data directory.
    Set SPOTR_DATA_DIR or pass --data-dir to use a custom location.
  EOS
end
