# This file was generated by GoReleaser. DO NOT EDIT.
cask "spotr" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "5300427f205b5a321a52c1c55a9ca197b8ed229ed01af27344d0b5aa9de10966"
      url "https://github.com/Yokanater/spotr/releases/download/v#{version}/spotr_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "da6386a7350cfa239eec062f219eeaf87093567e7e82d0e335b3572f20143bac"
      url "https://github.com/Yokanater/spotr/releases/download/v#{version}/spotr_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "01c06af2eaf275c955c39208e6e0892c61d43ab0d2aa4c83731444749d7e9304"
      url "https://github.com/Yokanater/spotr/releases/download/v#{version}/spotr_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "1d13999968588ce081757fdc4cf8ed5d3b7e12eee518efe2ecc7bc174ac8df2e"
      url "https://github.com/Yokanater/spotr/releases/download/v#{version}/spotr_Linux_arm64.tar.gz"
    end
  end

  name "spotr"
  desc "Workout logging for nerds on the terminal"
  homepage "https://github.com/Yokanater/spotr"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "spotr"

  # No zap stanza required

  caveats <<~EOS
    spotr stores spotr.db in the directory where you run it.
  EOS
end
