# This file was generated by GoReleaser. DO NOT EDIT.
cask "spotr" do
  version "0.2.1"

  on_macos do
    on_intel do
      sha256 "4cca504de889368332e3826af583d4a12bfc9fb0df2ad0820aacf9828a475d37"
      url "https://github.com/Yokanater/spotr/releases/download/v#{version}/spotr_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "ea53cb3af95d2a7e855ef6d16c51f469b179830c97070a8f2dc64feaa1c1442c"
      url "https://github.com/Yokanater/spotr/releases/download/v#{version}/spotr_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "695352ce5422d36bcd01d42a012adf25efa79f67c334bc5eb27e8e7f0a272b11"
      url "https://github.com/Yokanater/spotr/releases/download/v#{version}/spotr_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "dfc42c31457967ae5a7e6bcf9ed54b8bb48142a16c8f044dc135a97b7f5a895d"
      url "https://github.com/Yokanater/spotr/releases/download/v#{version}/spotr_Linux_arm64.tar.gz"
    end
  end

  name "spotr"
  desc "Workout logging for nerds on the terminal"
  homepage "https://spotr.info"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "spotr"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr",
                     args: ["-dr", "com.apple.quarantine", "#{staged_path}/spotr"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    spotr stores its database in your operating system's user data directory.
    Set SPOTR_DATA_DIR or pass --data-dir to use a custom location.
  EOS
end
